### ISSUE TITLE
MapNode isDiagonally method

### ISSUE THREAD

**Issue by MartinLundDam** [SE-F24-SP4/semesterproject-4#100]
I want a method: public boolean isMapNodeDiagonal(MapNode CurrentNode); 

This method will check if the next node that will be opened is diagonally adjacent or direct adjacent to the CurrentNode.
I need this, to update the gCost for a Node, because: 
- If a node is direct adjacent the gCost should be +1.
- If a node is diagonally adjacent the gCost should be +root(2).

I will make the above check. So the method just needs to check if it is diagonally adjacent or direct adjacent to the CurrentNode.
#27

**Comment by MidnightRocket** [comment]
I do not see how the cost of traversing diagonally is any different than traversing perpendicularly. 
And any cost difference should be reflected in the heuristics right?.
Otherwise could you maybe base the `gCost` on distance between the coordinates returned?

**Comment by MartinLundDam** [comment]
I suppose that the distance to travel is larger when moving diagonal for an enemy, and therefor the gCost, should be larger that moving to direct neighboring nodes?

**Comment by MidnightRocket** [comment]
But the distance travelled can easily be calculated given the coordinates which are returned by [`getSafeCoordinatesForEntity`](https://github.com/SE-F24-SP4/semesterproject-4/blob/bb9593dad4eafd2eedd8cdb11770aab68f3df3d0/CommonAI/src/main/java/com/github/sef24sp4/common/ai/map/MapNode.java#L27) method

**Comment by MartinLundDam** [comment]
How would I use getSafeCoordinatesForEntity(), in an algorithm to get a safe distance towards a Node. 
Where would I get a "final ICollidableEntity entity" from in a method that has nothing to do with Entities? 
Should I convert a Node into a ICollidableEntity? 
With these parameters, it seem like the method is meant to be used by an Enemy when moving and not when calculating a path.

**Comment by MidnightRocket** [comment]
Resovled by #116 
And https://github.com/SE-F24-SP4/semesterproject-4/commit/7678f1b631bac044d6d6d0a15ea6f6143f5043cb#diff-99121b23b94c5724b2d00c82d614bb0fcacebfab4318eed2b0af06e60f70304f
