### ISSUE TITLE
IVector features

### ISSUE THREAD

**Issue by FearfulSnow** [SE-F24-SP4/semesterproject-4#85]
# Missing features 
- isZero()
  - to check before dividing by zero
- normalize()
  - normalize before scalling, instead of using getNorm and then dividing each coordinate.
- scale()
  - to scale the point in the vector direction
- add() / subtract()
  - instead of saying coordinate.getX + otherCoordinate.getX AND coordinate.getY + otherCoordinate.getY,  same goes for subtract 
> I know that getVectorTo inside Coordinate class uses a subtract like implementation.

Some of these features could be implemented in Coordinates if these features is unfit in IVector

**Comment by MidnightRocket** [comment]
I don't quite get the use case of `.isZero()` method. I don't think vectors mathematics has a concept of [division](https://physics.stackexchange.com/a/111668). 
If you mean division of the individual x and y components, then I think it is more appropriate to implement locally where needed.

**Comment by MidnightRocket** [comment]
With regards to the `.normalize()` method I think it would be by far more appropriate to have `getNormalizedVector()` or similar, which returns a new but normalized version of the vector, rather than turning the existing vector into a normalized version.

**Comment by FearfulSnow** [comment]
.isZero is to return a boolean if the vector is close to zero with a tolerance level so we don't make calculation on something that has values as 0.0000001, for the normalize method I think it is a good approach.

**Comment by FearfulSnow** [comment]
The isZero method could look something like this
```
    public boolean isZero() {
        double tolerance = 1e-10;
        return getNorm() < tolerance;
    }
```

**Comment by MidnightRocket** [comment]
But who should define the tolerance? Is the tolerance hard coded? Or is it not better to locally decide when a vector is too small

**Comment by FearfulSnow** [comment]
we are talking about a tolerance level you can't even see, but if you think that this is a stupid method, then forget it, the other methods are more important.

**Comment by MidnightRocket** [comment]
The problem is that different usages have different tolerances. For instance PolygonEnemy might have a tolerance as high as `speed / 2`, as when the distance to the target point is less than this, it does not make much sense to move the PolygonEnemy.
